[package]
name = "bencode"
version = "0.1.0"
authors = ["Federico Morrone <contact@morrone.dev>"]
edition = "2021"

[dependencies]
atoi = "0.4.0"
nom = "7.0.0"
thiserror = "1.0.30"
indexmap = { version = "1.7.0", optional = true }

[dev-dependencies]
anyhow = "1.0.44"
metainfo = { path = "../metainfo" }

