name: ci
on: [push, pull_request]

jobs:
  test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust-version: [stable, beta, nightly]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust-version }}
      - name: Install nextest to run tests
        uses: taiki-e/install-action@nextest
      - name: Run tests
        run: cargo nextest run

  miri:
    name: Build and test with miri
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust-version: [nightly]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust-version }}
          components: miri
      - name: Install nextest to run tests
        uses: taiki-e/install-action@nextest
      - name: Run tests with miri
        run: cargo miri nextest run
